version: '3.7'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: always
  app:
    image: daneker/kotlin-rest
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/postgres
    depends_on:
     - postgres
    ports:
      - "8080:8080"